### PR TITLE
Fix types in APIClient

### PR DESCRIPTION
**Pull request by szepeviktor**
and a nasty return+else

props. @phpstan

### CODE REVIEW

**Comment by papakai** [comment]
Thanks for forwarding phpstan, I'll check that.

**Comment by szepeviktor** [comment]
> Thanks for forwarding phpstan,

PHPStan is a software :) not a human :)

**Comment by papakai** [comment]
Yes, I already recognized that, thanks :-) Always good to know more / better tools / apps for code verification & validation.
CodeSniffer is already doing fine, but doesn't detect all issues.

**Comment by szepeviktor** [comment]
> Always good to know more

See the notes on this https://github.com/szepeviktor/debian-server-tools/blob/master/webserver/Continuous-integration-Continuous-delivery.md
Please lay down while reading is, you may fall sleep.

**Comment by papakai** [comment]
oh wow - had been a lot of work I think :-) well done, I'll give it a read (just time is my problem). You got a star for your work!

**Comment by papakai** [comment]
be so kind to rebase you branches, I reviewed the unit tests so that they no longer fail. tia!

**Comment by szepeviktor** [comment]
All green 🍏

**Pull request merged**
