### PR TITLE
Use APT addon of TravisCI

### PR DESCRIPTION
**Pull request by szepeviktor**
Plus: as we have no lock file we need to do an `update`

### CODE REVIEW

**Comment by szepeviktor** [comment]
`testLoginRoleCredsOK` failes as - I think - there are no secrets for PRs

**Comment by papakai** [comment]
Thanks @szepeviktor , I'll dive into reviewing your PR's today.
This test is failing because that used role user has been deleted. We will deactivate that specific test temporarily and will review in near future.

**Comment by szepeviktor** [comment]
@papakai We have a saying here in Hungary:
_Simple as a wooden wedge_

**Comment by papakai** [comment]
You brought up important things - which I have to roll out over several repositories now :trophy:

**Comment by szepeviktor** [comment]
You're welcome.

**Pull request merged**
